"""
Generate datasets whose labels come from a quantum circuit.

The features are a plain classical vector :math:`x \\in [0,1]^n` drawn uniformly --
nothing quantum about them. What is quantum is the *label*: :math:`x` is encoded
into a state by a feature map, that state is evolved under a random Heisenberg
Hamiltonian for a time :math:`\\tau`, and the label is
:math:`\\mathbb{1}[\\langle Z_0 \\rangle > \\mathrm{median}]`. So the concept a
learner has to fit is a circuit's output, while the input it sees is ordinary
tabular data.

Two encodings are available. ``'zz'`` is the standard ``ZZFeatureMap``
(Havlicek et al., Nature 567, 209, 2019), re-implemented natively here and checked
against Qiskit's to 1e-15 by the test suite. ``'evo'`` is a Hamiltonian-evolution
encoding -- this module's own definition, *not* the E3 encoding of Huang et al.

Because the label was generated by a specific encoder, **the encoder a learner uses
must match it**. Two things break that match, and both are recorded in the
metadata so a mismatch can be caught after the fact rather than mistaken for a
result:

* **Scaling.** The inputs are already in :math:`[0,1]`, the range the label
  generator used. A pipeline that rescales them per training fold feeds the encoder
  different angles than the ones the labels came from, so QProfiler must run with
  ``scaling: false`` on these datasets.
* **Circuit depth.** QSVC's default feature map is ``reps=2``/``linear`` while
  PQK's is ``reps=4``/``pairwise``. A ``reps`` mismatch alone was enough to remove
  the measured advantage on ``ql_zz``, which is why the runsheet generates both
  depths as separate datasets.

Only ``x_view`` is written: the features are the classical vector, and there is no
second view to contrast against.
"""

import itertools

import numpy as np

from .quantum_core import (
    DATA_MAPS,
    ENTANGLEMENTS,
    Pauli,
    as_float_list,
    as_list,
    blas_limit,
    ensure_unique_names,
    evo_encoding_state,
    expvals,
    heisenberg_terms,
    pauli_sum,
    reject_name_for_sweep,
    threshold,
    write_dataset,
    zz_feature_state,
)

#: Parameters varied across the default sweep.
N_QUBITS = [8]
N_SAMPLES = [400]
ENCODING = ["zz"]
TAU = [1.0]

#: Encodings :func:`generate_quantum_label_datasets` accepts.
ENCODINGS = ("zz", "evo")


def _quantum_label_name(n, encoding, tau, seed, data_map="qiskit"):
    """The default dataset name for one configuration.

    The ``data_map`` suffix is appended only for the non-default map, and only
    for the ``'zz'`` encoding that has a data map at all, so every name
    generated before that option existed is unchanged.
    """
    suffix = "" if (data_map == "qiskit" or encoding != "zz") else f"_dm{data_map}"
    return f"ql_{encoding}_n{n}_tau{tau:g}_s{seed}{suffix}"


def _quantum_label_dataset(save_path, name, n, n_rows, encoding, tau, reps, entanglement,
                           margin, seed, blas_threads, data_map):
    """Build and write one quantum-label dataset."""
    rng = np.random.default_rng(seed)
    with blas_limit(n, blas_threads):
        X = rng.uniform(0, 1, size=(n_rows, n))
        Hh = pauli_sum(n, heisenberg_terms(n, rng)).toarray()
        E, V = np.linalg.eigh(Hh)
        U = (V * np.exp(-1j * E * tau)) @ V.conj().T
        obs = [Pauli(n, {0: "Z"})]
        F = []
        for x in X:
            psi = (zz_feature_state(x, reps, entanglement, data_map) if encoding == "zz"
                   else evo_encoding_state(x))
            F.append(expvals(U @ psi, obs)[0, 0])
        F = np.array(F)
        thr, keep = threshold(F, margin)
        y = (F > thr).astype(int)
        meta = dict(family="ql", n=n, encoding=encoding, reps=reps, entanglement=entanglement,
                    data_map=data_map if encoding == "zz" else None, tau=tau,
                    label_rule="1[<Z0> > median] after exp(-i H_heis tau) U_enc(x)|0>",
                    threshold=thr, margin=margin, seed=seed,
                    note="run with scaling off (inputs already in [0,1]) if encoder alignment matters")
        return write_dataset(save_path, name, X[keep], [f"x{i}" for i in range(n)],
                             y[keep], F[keep], meta)


def generate_quantum_label_datasets(
    n_qubits=N_QUBITS,
    n_samples=N_SAMPLES,
    encoding=ENCODING,
    tau=TAU,
    reps=2,
    entanglement="linear",
    margin=0.0,
    save_path=None,
    name=None,
    random_state=0,
    blas_threads=1,
    data_map="qiskit",
):
    """
    Generate datasets with classical features and circuit-generated labels.

    Sweeps the Cartesian product of ``n_qubits``, ``n_samples``, ``encoding``,
    ``tau`` and ``random_state``, writing one dataset per combination.

    Parameters
    ----------
    n_qubits : int or list of int, default=[8]
        Qubit counts, which are also the feature counts.
    n_samples : int or list of int, default=[400]
        Rows per dataset, before ``margin`` filtering.
    encoding : {'zz', 'evo'} or list of str, default=['zz']
        Feature map turning ``x`` into a state. ``'zz'`` is the standard
        ``ZZFeatureMap``; ``'evo'`` is the Hamiltonian-evolution encoding defined in
        :mod:`~qbiocode.data_generation.quantum_core`.
    tau : float or list of float, default=[1.0]
        Evolution time under the random Heisenberg Hamiltonian, applied after the
        encoding. Longer times mix the encoded state more.
    reps : int, default=2
        Feature-map repetitions, i.e. circuit depth. Not swept: it does not appear
        in the dataset name, so varying it would collide. Use one call per depth,
        as the documented runsheet does. Ignored by the ``'evo'`` encoding but
        still recorded in the metadata.
    entanglement : {'linear', 'pairwise', 'full'}, default='linear'
        Entanglement pattern of the ``'zz'`` feature map. Not swept, for the same
        reason as ``reps``.
    margin : float, default=0.0
        Drop rows whose continuous target lies within ``margin`` of the threshold.
    save_path : str, optional
        Directory to write into; defaults to ``'quantum_data'``.
    name : str, optional
        Override the generated dataset name. Only valid when the sweep yields a
        single dataset.
    random_state : int or list of int, default=0
        Seed, or seeds to sweep over. It sets both the inputs and the Heisenberg
        Hamiltonian.
    blas_threads : int or None, default=1
        BLAS threads for the linear algebra. Pass ``None`` to leave threading
        untouched.
    data_map : {'qiskit', 'unit'}, default='qiskit'
        Data map of the ``'zz'`` feature map, which decides *which* QProfiler
        model this family is aligned with: ``'qiskit'`` for ``qsvc``, ``'unit'``
        for ``pqk``. Ignored by the ``'evo'`` encoding, which has no data map,
        and recorded as ``None`` in its metadata. Not swept; the non-default
        value adds a ``_dmunit`` suffix to the dataset name. See
        :func:`~qbiocode.data_generation.quantum_core.zz_feature_state`.

    Returns
    -------
    list of dict
        The metadata written for each dataset.

    Raises
    ------
    ValueError
        If ``encoding`` is not one of ``'zz'`` or ``'evo'``; if ``data_map`` is not
        one of ``'qiskit'`` or ``'unit'``; if ``name`` is given for a sweep of more
        than one configuration; or if the sweep would write two datasets to the
        same name.

    Notes
    -----
    Only ``x_view`` is written, with columns ``x0 … x{n-1}``. These datasets must
    reach the quantum kernel **unscaled** -- see the module docstring.

    Examples
    --------
    >>> from qbiocode.data_generation import generate_quantum_label_datasets
    >>> generate_quantum_label_datasets(n_qubits=4, n_samples=32,
    ...                                 save_path='qdata')          # doctest: +SKIP
    Generating quantum-label datasets...
    """
    print("Generating quantum-label datasets...")
    if save_path is None:
        save_path = "quantum_data"
    encodings = as_list(encoding)
    unknown = [e for e in encodings if e not in ENCODINGS]
    if unknown:
        raise ValueError(
            f"unknown encoding(s) {unknown}; choose from {list(ENCODINGS)}. The label "
            f"depends on the encoder, so a silent fallback would change the concept."
        )
    if data_map not in DATA_MAPS:
        raise ValueError(
            f"data_map must be one of {list(DATA_MAPS)}, got {data_map!r}. "
            "'qiskit' targets QProfiler's qsvc, 'unit' targets its pqk. "
            "Ignored by the 'evo' encoding, which has no data map."
        )
    if entanglement not in ENTANGLEMENTS:
        # Checked here rather than left to zz_feature_state: the 'evo' encoding never
        # reaches the feature map, so a typo would pass silently and be recorded in
        # the metadata as though it had been used.
        raise ValueError(
            f"unknown entanglement {entanglement!r}; choose from {list(ENTANGLEMENTS)}."
        )
    configurations = list(itertools.product(
        as_list(n_qubits), as_list(n_samples), encodings, as_float_list(tau), as_list(random_state)
    ))
    reject_name_for_sweep(
        name, len(configurations), ["n_qubits", "n_samples", "encoding", "tau", "random_state"]
    )
    names = [name or _quantum_label_name(n, enc, t, seed, data_map)
             for n, _, enc, t, seed in configurations]
    ensure_unique_names(names, unnamed_knobs=["n_samples"])
    metas = []
    for (n, n_rows, enc, t, seed), dataset_name in zip(configurations, names):
        metas.append(_quantum_label_dataset(
            save_path, dataset_name, n, n_rows, enc, t, reps, entanglement,
            float(margin), seed, blas_threads, data_map,
        ))
    return metas
